### ISSUE TITLE
Make pipelines public?

### ISSUE THREAD

**Issue by zachgersh** [18F/cg-pipelines#13]
Hey All,

Your pipeline.yml files are all public via this repo but sadly when I go visit:

[https://ci.cloud.gov](https://ci.cloud.gov)

I can't view any of the pipelines because it has been blocked via auth.

Maybe it would be nice to expose the pipelines but keep auth for the build logs?

Details here on how to do that (toward the bottom for the page):

[http://concourse.ci/authentication.html](http://concourse.ci/authentication.html)

cc @LinuxBozo

**Comment by dlapiduz** [comment]
@zachgersh thanks for your interest in the pipelines. We usually keep everything open but due to the fact that we are still trying out concourse we want to keep the pipelines private.

I understand that the build logs can be protected but we haven't had the time to do our due diligence on how we can make things public without exposing any sensitive information.

**Comment by mogul** [comment]
> I understand that the build logs can be protected but we haven't had the time to do our due diligence on how we can make things public without exposing any sensitive information.

...which is not to say that we won't in time.

**Comment by dlapiduz** [comment]
oh we totally will... its just a matter of making sure that we take care of things beforehand.
